function createfigure(X1, Y1)
%CREATEFIGURE(X1, Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 13-Jun-2016 14:02:33

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'FontSize',18);
box(axes1,'on');
hold(axes1,'on');

% Create plot
plot(X1,Y1,'Color',[1 0 0]);

% Create xlabel
xlabel('Wavenumber cm^{-1}','FontWeight','bold','FontSize',20);

% Create ylabel
ylabel('Absorbance (A.U.)','FontWeight','bold','FontSize',20);

% Create title
title('FT-IR spectroscopy','FontWeight','bold','FontSize',22);

