function [fitresult, gof] = incubation3dplot(depth, time, resp_depth_hour_ave)
%CREATEFIT(DEPTH,TIME,RESP_DEPTH_HOUR_AVE)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : depth
%      Y Input : time
%      Z Output: resp_depth_hour_ave
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 07-Nov-2017 12:00:37


%% Fit: 'untitled fit 1'.
[xData, yData, zData] = prepareSurfaceData( depth, time, resp_depth_hour_ave );

% Set up fittype and options.
ft = 'cubicinterp';

% Fit model to data.
[fitresult, gof] = fit( [xData, yData], zData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, [xData, yData], zData );
legend( h, 'Fitted trend', 'Incubation dataset', 'Location', 'NorthEast' );
% Label axes
xlabel Time
ylabel Moisture
%set(gca,'ydir','reverse');
zlabel('Respiration rate (ug-C/g-soil/h)');
zlim([-0.5 12]);
%zlim([0 100]);
set(gca,'fontsize',16);
set(gca,'FontName','Times New Roman');
grid on
view( -18.0, 32.0 );


